In [1]:
import pandas as pd

In [12]:
tourism = pd.read_csv('C:\\Users\\Rushi\\Desktop\\Travel_Project\\tourism_data.csv')
flights = pd.read_csv('C:\\Users\\Rushi\\Desktop\\Travel_Project\\flights_data.csv')
hotels = pd.read_csv('C:\\Users\\Rushi\\Desktop\\Travel_Project\\hotels_data.csv')

In [13]:
tourism.head()

,Destination,State,Category,Best Season,Average Budget,Recommended Trip Duration,Latitude,Longitude,Nearest Airport,Popularity,Family Friendly,Adventure Score
0,Goa,Goa,Beach,Nov-Feb,30000,4,NaN,NaN,Goa Airport,High,Yes,6
1,Ladakh (Leh),Ladakh,Mountain,Mar-Jun,35000,5,NaN,NaN,Ladakh Airport,High,Yes,9
2,Jaipur,Rajasthan,Heritage,Oct-Mar,22000,3,NaN,NaN,Jaipur Airport,High,Yes,3
3,Varanasi (Kashi),Uttar Pradesh,Spiritual,Oct-Mar,18000,2,NaN,NaN,Varanasi Airport,High,Yes,2
4,Agra,Uttar Pradesh,Heritage,Oct-Mar,22000,3,NaN,NaN,Agra Airport,High,Yes,3

In [14]:
flights.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [15]:
hotels.head()

,Hotel_Name,Hotel_Rating,City,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Hotel_Price
0,Crowne Plaza Kochi,4.6,kochi,5-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Hot tub,Air conditioning,Fitness center,Spa,8854.0
1,Trident Hotel Cochin,4.5,kochi,5-star hotel,Free breakfast,Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Restaurant,6441.0
2,The Galaxy Suites,3.8,kochi,Apartment,Sleeps 10,Free parking,Free Wi-Fi,No air conditioning,No airport shuttle,No beach access,No elevator,No fireplace,831.0
3,The Renai cochin,4.2,kochi,4-star hotel,Free breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,2768.0
4,Ramada by Wyndham Kochi,4.5,kochi,5-star hotel,Breakfast,Free Wi-Fi,Free parking,Pool,Air conditioning,Fitness center,Spa,Bar,8938.0

In [20]:
print("Flight Destination Cities")
print(sorted(flights['destination_city'].unique()))

Flight Destination Cities
['Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Kolkata', 'Mumbai']

In [18]:
print("Hotel Cities")
print(list(sorted(hotels['City'].str.title().unique())))

Hotel Cities
['Ahmedabad', 'Allahabad', 'Amravati', 'Amritsar', 'Aurangabad', 'Bangalore', 'Bhubaneswar', 'Chandigarh', 'Chennai', 'Coimbatore', 'Dehradun', 'Delhi', 'Durgapur', 'Faridabad', 'Gandhinagar', 'Ghaziabad', 'Goa', 'Guwahati', 'Gwalior', 'Hazaribagh', 'Hyderabad', 'Indore', 'Jaipur', 'Jamshedpur', 'Kanpur', 'Kanyakumari', 'Kashmir', 'Kochi', 'Kolkata', 'Kumarakom', 'Lucknow', 'Ludhiana', 'Mangalore', 'Meerut', 'Mumbai', 'Mysore', 'Nagpur', 'Nashik', 'Noida', 'Patna', 'Pondicherry', 'Pune', 'Raipur', 'Ranchi', 'Sikkim', 'Srinagar', 'Trivandrum', 'Vadodara', 'Varanasi', 'Varkala', 'Vijayawada']

In [19]:
print("Tourism Destinations")
print(sorted(tourism['Destination'].unique()))

Tourism Destinations
['Agra', 'Agumbe', 'Almora & Kasar Devi', 'Amarkantak', 'Amboli Ghat', 'Amritsar', 'Araku Valley', 'Astaranga & Ramachandi', 'Auli', 'Bandhavgarh National Park', 'Bangaram & Kadmat', 'Binsar', 'Bodh Gaya', 'Chakrata', 'Cherrapunji', 'Chikmagalur', 'Chitkul & Baspa', 'Chitrakote Falls', 'Coorg (Kodagu)', 'Darjeeling', 'Dawki', 'Dhanushkodi', 'Dharamshala & McLeod Ganj', 'Gangtok', 'Goa', 'Gokarna', 'Great Rann of Kutch', 'Gulmarg', 'Hampi', 'Hampi & Pattadakal', 'Haridwar', 'Haridwar–Char Dham Trail', 'Havelock Island', 'Hidden Goa Coves', 'Jaipur', 'Jaisalmer', 'Jibhi & Tirthan', 'Kalpeni Island', 'Kanatal', 'Kanha National Park', 'Kanyakumari', 'Kaziranga', 'Keoladeo National Park', 'Kerala Backwaters (Alappuzha & Kumarakom)', 'Khajjiar', 'Khajuraho & Panna', 'Krang Suri Falls', 'Krishna Heritage Circuit', 'Kudremukh', 'Kutch Interior Circuit', 'Ladakh (Leh)', 'Lakshadweep Circuit', 'Mahabaleshwar & Panchgani', 'Majuli Island', 'Malanad–Malabar Belt', 'Mamallapuram', 'Manali', 'Maravanthe', 'Mawlynnong & nearby', 'Meghalaya Circuit', 'Miyar Valley', 'Munnar', 'Munsiyari', 'Nal Sarovar', 'Neil Island', 'North Sikkim', 'Nubra Valley', 'Ooty', 'Orchha', 'Pangong Lake', 'Pondicherry', 'Port Blair', 'Rameswaram', 'Ranganathittu Bird Sanctuary', 'Rann of Kutch', 'Ranthambore National Park', 'Rishikesh', 'Rishikesh & Haridwar Route', 'Shillong', 'Shimla', 'Spiti Valley', 'Tadoba Andhari Tiger Reserve', 'Tamhini Ghat & Mulshi', 'Tawang', 'Tiruvannamalai', 'Udaipur', 'Unakoti', 'Varanasi (Kashi)', 'Varanasi Ganga Ghats', 'Varkala', 'Wayanad', 'Ziro Valley']

In [21]:
data = pd.read_csv('C:\\Users\\Rushi\\Desktop\\Travel_Project\\Air-Clean.csv')

In [22]:
data.head()

,airline,flightNumber,origin,destination,daysOfWeek,scheduledDepartureTime,scheduledArrivalTime,timezone,validFrom,validTo,lastUpdated
0,GoAir,572,Goa,Hyderabad,"Thursday,Friday,Saturday",17:25,18:40,2021-03-27,2020-10-25,2021-03-27,2025-07-16
1,GoAir,301,Goa,Delhi,Saturday,12:00,14:45,2022-10-23,2022-03-27,2022-10-23,2025-07-16
2,GoAir,733,Goa,Nagpur,Saturday,12:10,13:40,2020-10-18,2020-03-29,2020-10-18,2025-07-16
3,GoAir,667,Goa,Lucknow,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",06:10,09:10,2019-10-26,2019-05-01,2019-10-26,2025-07-16
4,GoAir,247,Goa,Mumbai,Saturday,11:00,12:30,2022-03-20,2021-10-31,2022-03-20,2025-07-16

In [24]:
data['origin'].value_counts()

origin
Mumbai         2912
Delhi          2634
Bengaluru      2626
Hyderabad      2421
Kolkata        2204
               ...
Pakyong          11
Keshod            9
Bathinda          7
Pithoragarh       6
Cooch-Behar       3
Name: count, Length: 101, dtype: int64

In [41]:
data[(data["origin"] == "Hyderabad") & (data["destination"] == "Kochi")]

,airline,flightNumber,origin,destination,daysOfWeek,scheduledDepartureTime,scheduledArrivalTime,timezone,validFrom,validTo,lastUpdated
1639,GoAir,507,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",20:00,21:35,2020-03-28,2019-10-27,2020-03-28,2025-07-16
1671,Air India Express,1529,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",08:05,09:45,2019-03-30,2018-10-28,2019-03-30,2025-07-16
15726,IndiGo,169.0,Hyderabad,Kochi,Monday,19:50,21:25,2024-03-26,2023-10-31,2024-03-26,2025-07-16
15727,IndiGo,304.0,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",14:30,16:10,2019-10-26,2019-03-31,2019-10-26,2025-07-16
15728,IndiGo,6334.0,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",12:10,13:50,2021-03-27,2020-10-25,2021-03-27,2025-07-16
15729,IndiGo,667.0,Hyderabad,Kochi,Saturday,12:50,14:20,2019-10-20,2019-03-31,2019-10-20,2025-07-16
15730,IndiGo,6682.0,Hyderabad,Kochi,"Sunday,Wednesday,Thursday,Friday,Saturday",13:55,15:30,2025-03-29,2024-10-27,2025-03-29,2025-07-16
15731,IndiGo,6682.0,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",14:20,15:55,2024-10-26,2024-03-31,2024-10-26,2025-07-16
15732,IndiGo,6682.0,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",14:45,16:25,2023-03-25,2022-10-30,2023-03-25,2025-07-16
15733,IndiGo,6703.0,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",14:45,16:20,2022-10-29,2022-03-27,2022-10-29,2025-07-16
15734,IndiGo,6707.0,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",08:20,10:00,2022-03-26,2021-10-31,2022-03-26,2025-07-16
21186,IndiGo,169,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",19:30,21:05,2024-03-30,2023-10-29,2024-03-30,2025-07-16
21187,IndiGo,187,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",19:15,21:00,2020-10-24,2020-03-29,2020-10-24,2025-07-16
21188,IndiGo,304,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",14:30,16:10,2019-03-30,2018-10-28,2019-03-30,2025-07-16
21189,IndiGo,6234,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",11:15,12:55,2025-10-25,2025-03-30,2025-10-25,2025-07-16
21190,IndiGo,6334,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",16:15,18:05,2024-10-26,2024-03-31,2024-10-26,2025-07-16
21191,IndiGo,6334,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",19:55,21:25,2022-10-29,2022-03-27,2022-10-29,2025-07-16
21192,IndiGo,6682,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",13:55,15:35,2024-03-30,2023-10-29,2024-03-30,2025-07-16
21193,IndiGo,6684,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",18:15,19:50,2024-03-30,2023-10-29,2024-03-30,2025-07-16
21194,IndiGo,6707,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",09:15,10:50,2025-03-29,2024-10-27,2025-03-29,2025-07-16
21195,IndiGo,6707,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",09:55,11:35,2025-10-25,2025-03-30,2025-10-25,2025-07-16
21196,IndiGo,752,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",07:05,08:45,2025-10-25,2025-03-30,2025-10-25,2025-07-16
21197,IndiGo,764,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",20:45,22:20,2024-03-30,2023-10-29,2024-03-30,2025-07-16
23616,GoAir,506,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",19:30,21:05,2022-03-26,2021-10-31,2022-03-26,2025-07-16
23732,SpiceJet,2964,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",17:50,19:35,2023-03-25,2022-10-30,2023-03-25,2025-07-16
23733,SpiceJet,407,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",14:05,15:30,2021-03-27,2020-10-25,2021-03-27,2025-07-16
23823,GoAir,506,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",19:55,21:30,2020-10-24,2020-03-29,2020-10-24,2025-07-16
23824,GoAir,701,Hyderabad,Kochi,Saturday,11:45,13:20,2019-03-24,2018-10-28,2019-03-24,2025-07-16
25544,Air India Express,1529,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",08:05,08:55,2019-03-30,2018-10-28,2019-03-30,2025-07-16
25545,Air India Express,1529,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",11:00,12:45,2019-10-26,2019-03-31,2019-10-26,2025-07-16
25623,IndiGo,187,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",19:25,21:00,2020-03-28,2019-10-27,2020-03-28,2025-07-16
25624,IndiGo,438,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",05:00,06:40,2023-10-28,2023-03-26,2023-10-28,2025-07-16
25625,IndiGo,6304,Hyderabad,Kochi,Monday,16:35,18:15,2019-10-22,2019-04-02,2019-10-22,2025-07-16
25626,IndiGo,6684,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",18:40,20:15,2024-10-26,2024-03-31,2024-10-26,2025-07-16
25627,IndiGo,683,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",10:30,12:10,2019-10-26,2019-03-31,2019-10-26,2025-07-16
27708,GoAir,507.0,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",15:55,17:40,2022-10-29,2022-03-27,2022-10-29,2025-07-16
27709,GoAir,507.0,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",21:15,22:50,2020-10-24,2020-03-29,2020-10-24,2025-07-16
29136,Air India Express,1529,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",10:20,11:55,2020-10-24,2020-03-29,2020-10-24,2025-07-16
29223,IndiGo,6187,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",10:30,12:20,2021-03-27,2020-10-25,2021-03-27,2025-07-16
29224,IndiGo,6304,Hyderabad,Kochi,Monday,16:35,18:10,2019-03-26,2018-10-30,2019-03-26,2025-07-16
29225,IndiGo,6334,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",22:05,23:40,2022-03-26,2021-10-31,2022-03-26,2025-07-16
29226,IndiGo,6487,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",15:20,16:55,2022-03-26,2022-01-03,2022-03-26,2025-07-16
29227,IndiGo,6682,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",14:15,15:55,2025-10-25,2025-03-30,2025-10-25,2025-07-16
29228,IndiGo,6684,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",18:40,20:20,2025-10-25,2025-03-30,2025-10-25,2025-07-16
29229,IndiGo,6707,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",09:45,11:20,2024-03-30,2023-10-29,2024-03-30,2025-07-16
29230,IndiGo,683,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",10:30,12:00,2019-03-30,2018-10-28,2019-03-30,2025-07-16
29382,SpiceJet,3832,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",13:40,15:45,2023-03-25,2022-10-30,2023-03-25,2025-07-16
30851,GoAir,581.0,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",06:50,08:55,2019-03-30,2018-10-28,2019-03-30,2025-07-16
30852,GoAir,591.0,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",20:25,21:15,2019-03-30,2018-10-28,2019-03-30,2025-07-16
32164,IndiGo,637.0,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",07:45,09:15,2024-10-26,2024-03-31,2024-10-26,2025-07-16
32165,IndiGo,645.0,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",20:45,22:20,2019-03-30,2018-10-28,2019-03-30,2025-07-16
32166,IndiGo,6645.0,Hyderabad,Kochi,Monday,23:15,00:45,2019-03-26,2018-10-30,2019-03-26,2025-07-16
32167,IndiGo,6684.0,Hyderabad,Kochi,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",18:20,19:55,2025-03-29,2024-10-27,2025-03-29,2025-07-16
32168,IndiGo,6707.0,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",09:00,10:40,2023-03-25,2022-10-30,2023-03-25,2025-07-16
32169,IndiGo,6707.0,Hyderabad,Kochi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",09:55,11:35,2024-10-26,2024-03-31,2024-10-26,2025-07-16